# Generated by Django 3.2.19 on 2023-06-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftx', '0002_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='John Smith', max_length=100),
            preserve_default=False,
        ),
    ]
