# Generated by Django 3.2.19 on 2023-06-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftx', '0003_portfolio_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Stocks'},
        ),
    ]
