# Generated by Django 3.2.19 on 2023-07-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftx', '0004_alter_stock_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='icon',
            field=models.ImageField(upload_to='stocks/'),
        ),
    ]
